###############################################################################
# Errorlib makefile
# Generated by gen_library_template.sh, for more information refer to:
# https://github.com/eagletrt/micro-libs/blob/master/README.md
#
# Generation date: 2024-08-23 14:16:07 +0200
# To use include this file in your Makefile as follows:
#     include path/to/library/root/dir/errorlib.mk
###############################################################################


###############################################################################
### DIRECTORIES                                                             ###
###############################################################################

# Root directory of the library
ERRORLIB_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

###############################################################################
### SOURCES                                                                 ###
###############################################################################

# List of all the library sources
ERRORLIB_C_SOURCES?=$(shell find $(ERRORLIB_DIR)src -name "*.c")

###############################################################################
### HEADERS                                                                 ###
###############################################################################

# List of all the library include directories
ERRORLIB_C_INCLUDE_DIRS?=$(shell find $(ERRORLIB_DIR)inc -type d)
# List of all the library include directories with the -I prefix
ERRORLIB_C_INCLUDE_DIRS_PREFIX?=$(addprefix -I, $(ERRORLIB_C_INCLUDE_DIRS))

