#ifndef CAN_MANAGER_CONFIG_H
#define CAN_MANAGER_CONFIG_H

// #define CAN_MGR_STM32_APPLICATION
#define CAN_MGR_N_CAN 2
#define CAN_MGR_TOTAL_CAN_RX_FIFOS 2
#define CAN_MGR_CAN_WAIT_ENABLED 0

#endif // CAN_MANAGER_CONFIG_H
